### ISSUE TITLE
Publish 2.1.0 to npm

### ISSUE THREAD

**Issue by mattlewis92** [ajoslin/angular-promise-tracker#69]
The current version published to npm is 2.0.1, thanks!

**Comment by smolyakoff** [comment]
++

**Comment by LoicMahieu** [comment]
+1 !

**Comment by duddu** [comment]
+1 plz!

**Comment by SunburnedGoose** [comment]
+1  We're using webpack and npm, and this would be prefered to relying upon git.

**Comment by ajoslin** [comment]
Published.

**Comment by ajoslin** [comment]
Apologies for the 1 year delay!

**Comment by mattlewis92** [comment]
Awesome, thank you! :+1:

**Comment by SunburnedGoose** [comment]
Thanks for the work.  I use it for http://github.com/DestinyItemManager/DIM btw.
